version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      - npm install
      # install dependencies

  build:
    commands:
      # run build script
      - npm run build

  post_build:
    commands:
      # delete previous release
      - aws s3 rm s3://play.phishmeifyoucan.com/ --recursive
      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build s3://play.phishmeifyoucan.com/

artifacts:
  files:
    - "**/*"
  base-directory: "build"
